services:
  excalidraw:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      args:
        - NODE_ENV=development
    container_name: excalidraw
    ports:
      - "3000:80"
    restart: on-failure
    stdin_open: true
    healthcheck:
      disable: true
    environment:
      - NODE_ENV=development
    volumes:
      - ../apps/web:/opt/node_app/apps/web:delegated
      - ../package.json:/opt/node_app/package.json
      - ../yarn.lock:/opt/node_app/yarn.lock
      - notused:/opt/node_app/apps/web/node_modules

volumes:
  notused:
