import { useSettingsStore } from "@/stores/settingsStore";

const zhCN = {
  settings: "设置",
  aiConfig: "AI 配置",
  appearance: "外观",
  embedManage: "嵌入管理",
  help: "帮助",
  changelog: "更新日志",
  library: "素材库",
  about: "关于",
  theme: "主题",
  light: "浅色",
  dark: "深色",
  system: "跟随系统",
  language: "语言",
  localPreferenceHint: "保存在浏览器本地，不同浏览器可有不同偏好",
  drawingSpace: "绘图空间",
  fileManager: "文件管理",
  users: "用户管理",
  editor: "编辑器",
  searchFiles: "搜索文件名…",
  updatedAt: "修改时间",
  createdAt: "创建时间",
  name: "名称",
  import: "导入",
  newFile: "新建",
  loadingFiles: "正在加载文件…",
  fileServiceUnavailable: "文件服务暂不可用",
  emptyFiles: "还没有任何绘图文件",
  importFile: "导入文件",
  createFirstFile: "创建第一个文件",
  aboutTitle: "关于 Drawing Space",
  aboutDesc: "本地优先的多格式绘图工作台，在同一界面管理白板、思维导图等文件，支持草稿、历史版本与网页嵌入。",
  aboutProductName: "产品名称",
  aboutVersionLabel: "当前版本",
  aboutStorage: "数据存储",
  aboutStorageValue: "文件与版本保存在服务端数据库；草稿、临时文件与偏好设置保存在浏览器本地。",
  aboutEditors: "支持的编辑器",
  aboutEditorsValue: "Excalidraw 白板、思维导图（MindMap）、纯文本等（按注册情况显示）",
  aboutBoundaryTitle: "当前限制",
  aboutBoundary1: "用户与权限管理仍为占位能力，默认以本地工作区使用。",
  aboutBoundary2: "多人实时协作、云端账号体系尚未提供。",
  aboutBoundary3: "部分 AI 与素材库能力依赖自行配置 API 端点。",
  aboutCreditsTitle: "致谢",
  aboutCredits: "核心编辑能力基于 Excalidraw、simple-mind-map 等开源项目构建。",
  changelogTitle: "更新日志",
  changelogDesc: "各版本面向用户的功能与行为变更摘要。完整记录见项目根目录 CHANGELOG.md。",
  changelogAdded: "新增",
  changelogChanged: "变更",
  changelogFixed: "修复",
  helpTitle: "帮助与常见问题",
  helpDesc: "快速了解主页、临时文件、保存与嵌入等常用操作。",
  helpQ1: "主页是做什么的？",
  helpA1: "主页用于总览工作区：查看统计、点击编辑器类型快速新建，或在「最近打开」中继续编辑。侧栏「主页」会切换到该页面，不会关闭已在后台打开的编辑器。",
  helpQ2: "什么是「临时」文件？",
  helpA2: "在主页或编辑器选择页点击类型即可创建，内容先以「临时」状态保存在浏览器，不会立刻出现在文件管理中。再次新建时若仍有未保存的临时内容，可选择继续编辑或丢弃并新建；丢弃后仍可在「最近打开」中找到。保存到服务器后变为普通文件。",
  helpQ3: "如何保存文件？",
  helpA3: "编辑时点击侧栏「保存」，或使用 Ctrl/⌘ + S。临时文件首次保存会创建服务器文件；已落库文件会同步内容与缩略图到服务器。",
  helpQ4: "「未保存」和「临时」有什么区别？",
  helpA4: "「临时」表示文件尚未入库，只存在于本地。「未保存」表示文件已在服务器上，但当前编辑内容比上次保存的更新，存在本地草稿。",
  helpQ5: "什么时候可以使用嵌入？",
  helpA5: "仅对已保存（非临时）的文件可创建嵌入 Token。在编辑器中打开该文件后，通过侧栏「嵌入」或设置中的嵌入管理配置允许域名与 iframe 代码。",
  helpQ6: "历史版本怎么用？",
  helpA6: "对已保存的文件，在编辑器中点击侧栏「历史」可查看自动归档的版本并恢复。恢复前若存在未保存草稿，系统会提示确认。",
  helpQ7: "离开编辑器时为什么会提示保存？",
  helpA7: "当已落库文件有本地草稿时，切换到主页、文件管理等视图会询问是否保存。临时文件可直接切换，内容仍保留在本地，直到你主动保存或清理浏览器数据。",
  helpQ8: "有哪些快捷键？",
  helpA8: "Ctrl/⌘ + S：保存当前文件。在 Excalidraw 编辑器内还可使用其自带的绘图快捷键（见编辑器菜单或官方文档）。",
  inviteUser: "邀请用户",
  manageAccounts: "管理系统账号与权限角色。",
  admin: "管理员",
  adminDesc: "管理用户、系统配置和权限",
  editorRole: "编辑者",
  editorRoleDesc: "创建和编辑自己的文档",
  guest: "访客",
  guestDesc: "仅使用本地工作空间",
} as const;

const en: Record<keyof typeof zhCN, string> = {
  settings: "Settings",
  aiConfig: "AI Config",
  appearance: "Appearance",
  embedManage: "Embed",
  help: "Help",
  changelog: "Changelog",
  library: "Library",
  about: "About",
  theme: "Theme",
  light: "Light",
  dark: "Dark",
  system: "System",
  language: "Language",
  localPreferenceHint: "Saved locally in this browser.",
  drawingSpace: "Drawing Space",
  fileManager: "Files",
  users: "Users",
  editor: "Editor",
  searchFiles: "Search files...",
  updatedAt: "Updated",
  createdAt: "Created",
  name: "Name",
  import: "Import",
  newFile: "New",
  loadingFiles: "Loading files...",
  fileServiceUnavailable: "File service unavailable",
  emptyFiles: "No drawing files yet",
  importFile: "Import file",
  createFirstFile: "Create first file",
  aboutTitle: "About Drawing Space",
  aboutDesc: "A local-first workspace for Excalidraw, mind maps, and more—drafts, version history, and embed sharing in one shell.",
  aboutProductName: "Product",
  aboutVersionLabel: "Version",
  aboutStorage: "Storage",
  aboutStorageValue: "Files and archives on the server; drafts, temp files, and preferences in the browser.",
  aboutEditors: "Editors",
  aboutEditorsValue: "Excalidraw, MindMap, plain text, and others as registered.",
  aboutBoundaryTitle: "Current limits",
  aboutBoundary1: "User and permission management is still a placeholder.",
  aboutBoundary2: "No real-time multiplayer or cloud accounts yet.",
  aboutBoundary3: "Some AI and library features require your own API endpoint.",
  aboutCreditsTitle: "Credits",
  aboutCredits: "Built on Excalidraw, simple-mind-map, and other open-source projects.",
  changelogTitle: "Changelog",
  changelogDesc: "User-facing changes by release. See CHANGELOG.md in the repo for the full log.",
  changelogAdded: "Added",
  changelogChanged: "Changed",
  changelogFixed: "Fixed",
  helpTitle: "Help & FAQ",
  helpDesc: "How home, temp files, save, embed, and history work.",
  helpQ1: "What is the home page?",
  helpA1: "Overview and quick start: stats, create by editor type, and recent files. The sidebar Home item switches to this view without closing an open editor.",
  helpQ2: "What is a temp file?",
  helpA2: "Create from Home or the editor picker; content stays local with a Temp badge until Save. Starting another new file while one is open prompts you to continue or discard; discarded temps remain in Recents.",
  helpQ3: "How do I save?",
  helpA3: "Use the sidebar Save button or Ctrl/⌘+S. The first save of a temp file creates the server file; saved files sync content and thumbnails.",
  helpQ4: "Temp vs unsaved?",
  helpA4: "Temp means not on the server yet. Unsaved means the file exists on the server but local edits are newer than the last save.",
  helpQ5: "When can I embed?",
  helpA5: "Only after a file is saved (not temp). Open it in the editor, then use Embed in the sidebar or Settings.",
  helpQ6: "Version history?",
  helpA6: "For saved files, open History in the sidebar to list archives and restore. You will be warned if local drafts exist.",
  helpQ7: "Why save before leaving?",
  helpA7: "Server files with local drafts prompt when switching views. Temp files can switch freely; data stays local until you save.",
  helpQ8: "Shortcuts?",
  helpA8: "Ctrl/⌘+S saves the active file. Excalidraw has its own drawing shortcuts inside the editor.",
  inviteUser: "Invite user",
  manageAccounts: "Manage accounts and permission roles.",
  admin: "Admin",
  adminDesc: "Manage users, system settings, and permissions",
  editorRole: "Editor",
  editorRoleDesc: "Create and edit personal documents",
  guest: "Guest",
  guestDesc: "Use the local workspace only",
};

export type UiTextKey = keyof typeof zhCN;

export function useUiText() {
  const language = useSettingsStore((state) => state.language);
  const dictionary = language === "en" ? en : zhCN;
  return (key: UiTextKey) => dictionary[key];
}
